services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - shared_volume:/rest-api/csvdb
    restart: unless-stopped

  rest-api:
    build:
      context: .
      dockerfile: docker/Dockerfile1
    env_file:
      - .env
    ports:
      - $REST_API_PORT:$REST_API_PORT
    volumes:
      - ./tools:/tools:ro
      - shared_volume:/rest-api/csvdb
    command: >
      sh -c "/tools/wait-for-it/wait-for-it.sh $POSTGRES_HOST:$POSTGRES_PORT -t 0 &&
             ./cpp_crud_rest_api_experiments"

    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  shared_volume: